<?php
/**
 * Copyright (c) 2024.
 * wot2304@gmail.com
 * Yanis Yeltsyn
 */

declare(strict_types=1);
/**
 * Copyright (c) 2024.
 * wot2304@gmail.com
 * Yanis Yeltsyn
 */

/** @var Memo $block */
/** @var $escaper Escaper */

use Magento\Framework\Escaper;
use Mondu\Mondu\Block\Memo;

$invoices = $block->invoices();
$mapping = $block->getInvoiceMappings();
?>

<?php if ($block->render()): ?>
<div class="field choice admin__field">
    <?= $escaper->escapeHtml($block->getPaymentMethod()) ?>
    <div class="admin__field">
        <label for="history_status" class="admin__field-label">Invoice to memo</label>
        <div class="admin__field-control">
            <select name="creditmemo[creditmemo_mondu_id]" id="history_status" class="admin__control-select">
                <?php foreach ($mapping as $key => $item): ?>
                    <option value="<?= $escaper->escapeHtml($item['uuid']) ?>"
                        <?php
                            (isset($item['state']) && $item['state'] === 'complete') ?
                            $escaper->escapeHtml('disabled') :
                            ''
                        ?>
                    >
                        INVOICE: <?= $escaper->escapeHtml($key) ?> State: <?= $escaper->escapeHtml($item['state']) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>
<?php endif; ?>
